name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Set working directory
      run: cd pinger

    - name: Download dependencies
      run: |
        cd pinger
        go mod tidy

    - name: Build
      run: |
        cd pinger
        go build -v ./...

    - name: Run tests
      run: |
        cd pinger
        go test -v ./...
